# Generated by Django 4.2.6 on 2024-01-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_main_post_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_post',
            field=models.BooleanField(default=False),
        ),
    ]
