# Generated by Django 4.2.6 on 2024-01-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_main_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=models.ImageField(default=2, upload_to='Author'),
            preserve_default=False,
        ),
    ]
